package com.sample.cep


import com.sample.cep.*;
import com.sample.process.*;

import gnu.io.CommPort;
import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;

import java.io.FileDescriptor;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;


declare ThermoSensorData
@role(event)
end

declare SmokeSensorData
@role(event)
end

declare DustSensorData
@role(event)
end

declare VibrationData
@role(event)
end

declare FingerPrintData
@role(event)
end


rule "High Dust Rule"
	no-loop true
	lock-on-active true
	when
		wv : writeValue()
		dsd: DustSensorData(dust > dsd.getDustLimit(), value: dust) from entry-point dust
	then
		wv.addWriteValue(dsd.getWriteValue());
end

rule "Low Dust Rule"
	no-loop true
	lock-on-active true
	when
		wv : writeValue()
		dsd: DustSensorData(dust <= dsd.getDustLimit(), value: dust) from entry-point dust
	then
		wv.subWriteValue(dsd.getWriteValue());
end
	
rule "High Smoke Rule"
	no-loop true
	lock-on-active true
	when
		wv : writeValue()
		ssd: SmokeSensorData(SmokeLevel > ssd.getSmokeLimit(), value: SmokeLevel) from entry-point gas
	then
		wv.addWriteValue(ssd.getWriteValue());
end
		
rule "Low Smoke Rule"
	no-loop true
	lock-on-active true
	when
		wv : writeValue()
		ssd: SmokeSensorData(SmokeLevel <= ssd.getSmokeLimit(), value: SmokeLevel) from entry-point gas
	then
		wv.subWriteValue(ssd.getWriteValue());
end
		
rule "Earthquake Rule"
	no-loop true
	lock-on-active true
	when
		wv : writeValue()
		vsd: VibrationData(Vibration > vsd.getVibrationLimit(), value: Vibration) from entry-point vibration
	then
		wv.addWriteValue(vsd.getWriteValue());
end
		
rule "Earthquake-end Rule"
	no-loop true
	lock-on-active true
	when
		wv : writeValue()
		vsd: VibrationData(Vibration <= vsd.getVibrationLimit(), value: Vibration) from entry-point vibration
	then
		wv.subWriteValue(vsd.getWriteValue());
end
